name: Release on version change

on:
  push:
    branches:
      - main

jobs:
  check-package-json-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check package.json and create release
        uses: marocchino/sticky-pull-request-comment@v2
        id: create_release
        with:
          message: "Creating new release..."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-commit: "/.+/"
      - name: Create GitHub Release
        if: steps.create_release.outputs.comment-created == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_VERSION: ${{ steps.create_release.outputs.package-version }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          tagName=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')
          if [[ -z "$tagName" ]]; then
            tagName="v${PACKAGE_VERSION}"
            echo "Tagging $tagName..."
            git tag $tagName -a -m "Version $tagName"
            echo "Pushing tag to GitHub..."
            git push origin $tagName
          else
            echo "Tag $tagName already exists. Skipping tag creation."
          fi
